In [1]:

#### 1. Import the numpy package under the name `np` (★☆☆)
import numpy as np

In [2]:
#### 2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)

1.26.3


In [3]:
#### 3. Create a null vector of size 10 (★☆☆)
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#### 4. How to find the memory size of any array (★☆☆)
arr = np.zeros((3, 4))
memory_size = arr.nbytes
print("Memory size of the array:", memory_size, "bytes")


Memory size of the array: 96 bytes


In [5]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
!pydoc numpy.add

Help on ufunc in numpy:

numpy.add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the

In [6]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)
print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)
vector = np.arange(10, 50)
reversed_vector = vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arr = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(arr)
print(indices)


(array([0, 1, 4]),)


In [12]:
#### 11. Create a 3x3 identity matrix (★☆☆)
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
#### 12. Create a 3x3x3 array with random values (★☆☆)
array = np.random.rand(3, 3, 3)
print(array)

[[[0.34100746 0.65879663 0.70599628]
  [0.37620897 0.86818749 0.87323466]
  [0.79142628 0.03447757 0.00635208]]

 [[0.59321692 0.52021911 0.50691546]
  [0.30864591 0.51713249 0.16812633]
  [0.03848898 0.17899934 0.20717099]]

 [[0.15483223 0.45581697 0.48032738]
  [0.30356457 0.50875553 0.93841093]
  [0.50480291 0.00984955 0.98788579]]]


In [14]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
array = np.random.rand(10, 10)
print("Array:")
print(array)

minimum_value = np.min(array)
maximum_value = np.max(array)

print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)

Array:
[[0.86523719 0.79592183 0.37460001 0.95056958 0.01341302 0.43714794
  0.11889904 0.1790426  0.54417137 0.88424074]
 [0.6542741  0.85352253 0.14933508 0.81040132 0.44602658 0.57695023
  0.8513847  0.23309108 0.72680002 0.32493702]
 [0.80545989 0.35513627 0.3440907  0.95839671 0.57859783 0.98117317
  0.19006178 0.1765507  0.90871731 0.46179938]
 [0.10516016 0.9681954  0.90090937 0.36191764 0.10617041 0.87603055
  0.1842952  0.98350442 0.59645109 0.75616274]
 [0.0725857  0.48902971 0.8387149  0.5905156  0.66771028 0.93370194
  0.31761899 0.47184365 0.95620413 0.26535803]
 [0.6358042  0.18483313 0.22299415 0.09532114 0.2897693  0.50787661
  0.12236361 0.00223746 0.47171674 0.36710931]
 [0.75979924 0.55003156 0.85349603 0.91243485 0.34241109 0.96883444
  0.39039342 0.40556782 0.93509767 0.43996251]
 [0.07333629 0.35333163 0.48357249 0.77236026 0.3831969  0.29176151
  0.74014822 0.88532066 0.03768095 0.0557009 ]
 [0.40741638 0.90933717 0.72250301 0.47065781 0.24907649 0.42465809
  0.5

In [15]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
import numpy as np

vector = np.random.rand(30)
print("Vector:")
print(vector)

mean_value = np.mean(vector)
print("Mean value:", mean_value)


Vector:
[0.49818324 0.1969117  0.46240718 0.93003293 0.73908796 0.68768924
 0.4386444  0.33848592 0.24820441 0.6522659  0.12937898 0.32071164
 0.46561913 0.72921067 0.21548519 0.86663282 0.82274788 0.36602372
 0.67951172 0.8684691  0.97424591 0.73631941 0.107913   0.26383568
 0.30257552 0.61467619 0.9100928  0.43574491 0.13905168 0.38317009]
Mean value: 0.517444297421716


In [16]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
rows = 5
cols = 5

array = np.zeros((rows, cols))
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

border_width = 1

padded_array = np.pad(existing_array, pad_width=border_width, mode='constant')

print("Existing Array:")
print(existing_array)

print("\nPadded Array:")
print(padded_array)

Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded Array:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [18]:
#### 17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [19]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
matrix = np.zeros((5, 5))
diagonal_values = [1, 2, 3, 4]

# Assign values just below the diagonal
np.fill_diagonal(matrix[1:], diagonal_values)

print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [20]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
matrix = np.zeros((8, 8), dtype=str)
matrix[::2, ::2] = "★"  # Set stars in even rows and even columns
matrix[1::2, 1::2] = "★"  # Set stars in odd rows and odd columns
print(matrix)

[['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']
 ['★' '' '★' '' '★' '' '★' '']
 ['' '★' '' '★' '' '★' '' '★']]


In [21]:
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

array_shape = (6, 7, 8)
total_elements = np.prod(array_shape)  # Compute the total number of elements in the array
element_index = 100

# Check if the element index is within the valid range
if element_index >= total_elements:
    print("Element index is out of range for the given array shape.")
else:
    # Compute the index (x, y, z) of the element
    indices = np.unravel_index(element_index, array_shape)
    print("Index (x, y, z) of the 100th element:", indices)


Index (x, y, z) of the 100th element: (1, 5, 4)


In [22]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

base_pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(base_pattern, (4, 4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#### 22. Normalize a 5x5 random matrix (★☆☆)
random_matrix = np.random.random((5, 5))
normalized_matrix = np.linalg.norm(random_matrix)

print("Random Matrix:")
print(random_matrix)

print("\nNormalized Matrix:")
print(normalized_matrix)


Random Matrix:
[[0.91269816 0.9445402  0.78170261 0.98694607 0.79986149]
 [0.88342202 0.93282266 0.098863   0.46337616 0.91051782]
 [0.81637362 0.19932728 0.47069924 0.68154342 0.32334647]
 [0.29473278 0.12058298 0.44256159 0.96707158 0.48626399]
 [0.94650068 0.37647976 0.02536503 0.83521318 0.84239088]]

Normalized Matrix:
3.473529330559118


In [24]:
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
# Define the custom dtype
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
# Create a color array using the custom dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)
print(color_array)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


In [25]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((3, 2))

product = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Product:")
print(product)

Matrix 1:
[[0.61067419 0.40669423 0.24529205]
 [0.69147687 0.74627028 0.61184867]
 [0.94669967 0.31440522 0.86445669]
 [0.37567043 0.32163998 0.83739722]
 [0.80152347 0.79264891 0.34141645]]

Matrix 2:
[[0.8687649  0.09996198]
 [0.14062141 0.39867886]
 [0.96250211 0.14796691]]

Matrix Product:
[[0.82381634 0.2594797 ]
 [1.29457805 0.45717694]
 [1.69871294 0.34789168]
 [1.17759534 0.2896909 ]
 [1.13641291 0.44665258]]


In [26]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

arr = np.array([1, 5, 4, 9, 7, 2, 6, 3, 8])

# Find the indices of elements between 3 and 8
indices = np.where((arr >= 3) & (arr <= 8))

# Negate the elements at the found indices
arr[indices] = -arr[indices]

print(arr)

[ 1 -5 -4  9 -7  2 -6 -3 -8]


In [27]:
#### 26. What is the output of the following script? (★☆☆)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [29]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
"""Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z """

'Z**Z\n2 << Z >> 2\nZ <- Z\n1j*Z\nZ/1/1\nZ<Z>Z '

In [30]:
#### 28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_887/2409017176.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_887/2409017176.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_887/2409017176.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [31]:
#### 29. How to round away from zero a float array ? (★☆☆)

arr = np.array([-1.5, 2.3, -4.7, 5.9, -0.1])

rounded_arr = np.ceil(np.abs(arr)) * np.copysign(1, arr)

print(rounded_arr)

[-2.  3. -5.  6. -1.]


In [32]:
#### 30. How to find common values between two arrays? (★☆☆)

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(array1, array2)

print(common_values)


[4 5]


In [38]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

import numpy as np
import warnings

# Ignore all NumPy warnings
warnings.filterwarnings('ignore', category=FutureWarning)

# Reset warnings to default behavior
warnings.resetwarnings()

In [39]:
#### 32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

/tmp/ipykernel_887/306841201.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [40]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-06
Today: 2024-02-07
Tomorrow: 2024-02-08


In [41]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
from datetime import datetime, timedelta

def get_dates_in_month(year, month):
    start_date = datetime(year, month, 1).date()
    next_month = start_date.replace(day=28) + timedelta(days=4)  # Add 4 days to go beyond end of month
    end_date = next_month - timedelta(days=next_month.day)

    dates_in_month = []
    current_date = start_date
    while current_date <= end_date:
        dates_in_month.append(current_date)
        current_date += timedelta(days=1)

    return dates_in_month

# Get all the dates in July 2016
dates_july_2016 = get_dates_in_month(2016, 7)

# Print the dates
for date in dates_july_2016:
    print(date)


2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


In [43]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)


A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6])

# Compute ((A+B)*(-A/2)) in place
np.add(A, B, out=A)
np.negative(A, out=A)
np.divide(A, 2, out=A)

# Print the result
print(A)

[-2.5 -3.5 -4.5]


In [45]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
# Generate a random array of positive numbers
arr = np.random.rand(5) * 10  # Adjust the size of the array as needed

# Method 1: Using np.floor()
int_part_1 = np.floor(arr)
print("Method 1 (np.floor()):", int_part_1)

# Method 2: Using np.trunc()
int_part_2 = np.trunc(arr)
print("Method 2 (np.trunc()):", int_part_2)

# Method 3: Using np.ceil() and subtraction
int_part_3 = arr - (arr % 1)
print("Method 3 (np.ceil() and subtraction):", int_part_3)

# Method 4: Using np.astype()
int_part_4 = arr.astype(int)
print("Method 4 (np.astype()):", int_part_4)


Method 1 (np.floor()): [2. 8. 9. 0. 3.]
Method 2 (np.trunc()): [2. 8. 9. 0. 3.]
Method 3 (np.ceil() and subtraction): [2. 8. 9. 0. 3.]
Method 4 (np.astype()): [2 8 9 0 3]


In [46]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

# Create a 1-dimensional array ranging from 0 to 4
row_values = np.arange(5)

# Create a 5x5 matrix by broadcasting the row values
matrix = np.tile(row_values, (5, 1))

# Print the matrix
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [47]:
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def integer_generator():
    for i in range(10):
        yield i

# Create an array using the generator function
array = np.fromiter(integer_generator(), dtype=int)

# Print the array
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
vector = np.linspace(0, 1, 10, endpoint=False)[1:]

# Print the vector
print(vector)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [49]:
#### 40. Create a random vector of size 10 and sort it (★★☆)

# Create a random vector of size 10
vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(vector)

# Print the sorted vector
print(sorted_vector)


[0.15136732 0.22922223 0.26636518 0.34614265 0.45668899 0.64755181
 0.65429766 0.76620199 0.86676736 0.93446671]


In [53]:
#### 41. How to sum a small array faster than np.sum? (★★☆)
import math
arr = [1, 2, 3, 4, 5]
total = sum(arr)


arr = [1.1, 2.2, 3.3, 4.4, 5.5]
total = math.fsum(arr)


In [54]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)
# Generate two random arrays A and B
A = np.random.rand(5)
B = np.random.rand(5)

# Check if A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
print(are_equal)

False


In [56]:
#### 43. Make an array immutable (read-only) (★★☆)
mutable_array = np.array([1, 2, 3, 4, 5])

# Make the array immutable
immutable_array = mutable_array.copy()
immutable_array.flags.writeable = False

# Try to modify the immutable array (raises an error)
immutable_array[0] = 10


ValueError: assignment destination is read-only

In [57]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

# Create a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Convert Cartesian coordinates to polar coordinates
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.hypot(x, y)
theta = np.arctan2(y, x)

# Stack r and theta to form a 10x2 matrix representing polar coordinates
polar_coords = np.column_stack((r, theta))

# Print the polar coordinates
print(polar_coords)

[[0.72137793 0.07659608]
 [0.52718994 0.75339786]
 [1.17620382 0.87920234]
 [1.12093269 0.77136412]
 [0.96979514 0.58584751]
 [1.04094008 1.17857997]
 [0.97262223 0.7170525 ]
 [0.8625558  0.33960741]
 [0.71014822 0.62058519]
 [0.83412606 0.69300385]]


In [58]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
# Create a random vector of size 10
vector = np.random.rand(10)

# Find the maximum value in the vector
max_value = np.max(vector)

# Replace the maximum value with 0
vector[vector == max_value] = 0

# Print the updated vector
print(vector)

[0.00470444 0.45813354 0.45992459 0.23603075 0.08332563 0.46848198
 0.62062105 0.         0.59725239 0.36851303]


In [59]:
#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
# Define the number of points in each dimension
num_points = 5

# Create a grid of x and y coordinates
x_coords = np.linspace(0, 1, num_points)
y_coords = np.linspace(0, 1, num_points)
xx, yy = np.meshgrid(x_coords, y_coords)

# Create a structured array
structured_array = np.zeros((num_points*num_points,), dtype=[('x', float), ('y', float)])
structured_array['x'] = xx.flatten()
structured_array['y'] = yy.flatten()

# Print the structured array
print(structured_array)


[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


In [60]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Compute the Cauchy matrix
C = 1 / (X[:, np.newaxis] - Y)

# Print the Cauchy matrix
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [61]:
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
# Integer scalar types
integer_types = [np.int8, np.int16, np.int32, np.int64,
                 np.uint8, np.uint16, np.uint32, np.uint64]

for int_type in integer_types:
    info = np.iinfo(int_type)
    print(f"{int_type.__name__}: min={info.min}, max={info.max}")

# Floating-point scalar types
float_types = [np.float16, np.float32, np.float64]

for float_type in float_types:
    info = np.finfo(float_type)
    print(f"{float_type.__name__}: min={info.min}, max={info.max}")

int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


In [62]:
#### 49. How to print all the values of an array? (★★☆)

# Create an example array
arr = np.array([1, 2, 3, 4, 5])
# Print all the values of the array
print(arr)

[1 2 3 4 5]


In [63]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
# Example vector
vector = np.array([1, 4, 7, 10])

# Target scalar
target = 6

# Find the index of the closest value
index = np.abs(vector - target).argmin()

# Get the closest value
closest_value = vector[index]

# Print the closest value
print(closest_value)

7


In [64]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

# Define the structured data type
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', int), ('g', int), ('b', int)])])

# Create a structured array
structured_array = np.array([((1.0, 2.0), (255, 0, 0)),
                             ((3.0, 4.0), (0, 255, 0)),
                             ((5.0, 6.0), (0, 0, 255))], dtype=dtype)

# Print the structured array
print(structured_array)


[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]
